<a href="https://colab.research.google.com/github/dmitryglhf/Topomatic.LookUp/blob/main/lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Data

In [ ]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler

In [ ]:
#df = pd.read_csv('cancer_tumor_data_features.csv')

### QR-algorithm


In [ ]:
def householder(a):
    v = a.copy()
    v[0] += np.sign(v[0]) * np.linalg.norm(a)
    H = np.eye(len(a)) - 2 * np.outer(v, v) / np.dot(v, v)  # getting Householder matrix
    return H


def get_qr(A):
    n = A.shape[0]
    Q = np.eye(n)
    R = A.copy()

    for j in range(n):
        a = R[j:, j]  # getting vector
        H = householder(a)  # getting Householder matrix

        R[j:, j:] = H @ R[j:, j:]  # change R
        Q[:, j:] = Q[:, j:] @ H.T  # change Q

    return Q, R


def eig(A, e=1e-10):
    An = A.copy() # for eig values
    eig_vectors = np.eye(A.shape[0]) # for eig vectors
    cache_eig_values = np.diag(An) # diag values
    diff = 1000

    while diff > e:
        Q, R = get_qr(An)

        # update eigen values and eigen vectors
        An = R @ Q
        eig_vectors = eig_vectors @ Q

        # update difference between eig values
        current_eig_values = np.diag(An)
        diff = np.linalg.norm(current_eig_values - cache_eig_values)
        cache_eig_values = current_eig_values

    eig_values = np.diag(An)

    # sort eig_values and eig_vectors
    #sorted_key = np.argsort(eig_values)[::-1]
    #eig_values, eig_vectors = eig_values[sorted_key], eig_vectors[:,sorted_key]

    # return eigen values and eigen vectors
    return eig_values, eig_vectors

### SVD

In [ ]:
def svd(A):
    # V^T matrix
    temp_V = A.T @ A
    eig_values, V = np.linalg.eig(temp_V)  # Собственные значения и векторы для A^T A


    # U matrix
    temp_U = A @ A.T
    _, U = np.linalg.eig(temp_U)  # Собственные значения и векторы для A A^T

    # Sigma matrix
    sigma = np.zeros((A.shape[0], A.shape[1]))
    for i in range(min(A.shape[0], A.shape[1])):
      # тут может быть косяк с плавающей запятой:
      sigma[i, i] = np.sqrt(eig_values[i]) if eig_values[i] >= 0 else 0

    # Result
    return U, sigma, V.T

### Data Scaling

In [ ]:
scaler = StandardScaler()
scaled_X = scaler.fit_transform(df)
scaled_X.mean()

NameError: name 'df' is not defined

### PCA

In [ ]:
def pca(X):
  U, S, V_T = svd(X)

  # finding numer of PC
  sum = S[0][0]
  explained_ratio = sum / np.sum(np.diag(X))
  i = 1
  while(explaned_ratio <= 0.95):
    sum += S[i][i]
    explained_ratio = sum / np.sum(np.diag(X))
    i += 1

  # projection
  V_T_k = V_T[:i, :]  # берем первые k строк матрицы V_T
  X_pca = X @ V_T_k.T

  return X_pca

### Build the Neural Network

https://pytorch.org/tutorials/beginner/basics/buildmodel_tutorial.html#model-parameters

In [ ]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

#### Get Device for Training

In [ ]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

NameError: name 'torch' is not defined

#### Define the Class

In [ ]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

NameError: name 'nn' is not defined

In [ ]:
model = NeuralNetwork().to(device)
print(model)

NameError: name 'NeuralNetwork' is not defined

In [ ]:
X = torch.rand(1, 28, 28, device=device)
logits = model(X)
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")

### Test - functions

In [ ]:
def eig_test():
  '''
  eigen values for matrix A:
  l1 = -2
  l2 = 2
  l3 = 4

  eigen vectors for matrix A:
  v1 = (0, 1, -2)
  v2 = (2, -1, 0)
  v3 = (9, -2, 1)

  original: http://mathprofi.ru/sobstvennye_znachenija_i_sobstvennye_vektory.html
  '''

  A = np.array([[5, 6, 3],
                        [-1, 0, 1],
                        [1, 2, -1]], dtype = float)
  A=A.T@A
  print(f'Transposed origin matrix A: \n {A} \n ')
  eig_values, eig_vectors = eig(A)

  n = A.shape[0]

  for i in range(n):
      v = eig_vectors [:, i]
      norm_value = np.linalg.norm((A - eig_values[i] * np.eye(n)) @ v)

      print(f"Норма для собственного значения \
      λ{i+1} = {eig_values[i].round(3)}:\t {norm_value.round(3)}")

  print(f'\n Eigen vectors: \n {eig_vectors}')

def swap_columns(matrix, col1, col2):
    for row in matrix:
        row[col1], row[col2] = row[col2], row[col1]




def svd_test(A):
  #U, Sigma, V = np.linalg.svd(A)
  U, Sigma, V = svd(A)
  for row in U:
    row[1], row[2] = row[2], row[1]

  #Sigma = np.zeros((A.shape[0], A.shape[1]))  # Матрица того же размера, что и A
  #np.fill_diagonal(Sigma_matrix, Sigma)  # Заполнение диагонали матрицы значениями Sigma
  print(f'Origin matrix A: \n{A} \n ')
  print(f'Матрица левых сингулярных векторов U: \n {U.round(3)} \n ')
  print(f'Матрица сингулярных чисел Sigma: \n {Sigma.round(3)} \n ')
  print(f'Матрица правых сингулярных векторов V_T: \n {V.round(3)} \n ')
  print(f'Исходная матрица: \n {V.T @ Sigma @ U} \n ')

### Test

In [ ]:
  '''
  Для матрицы A_2x2:

  U = [[0.6, 0.8]
        [0.8, -0.6]]

  Sigma = [[3, 0]
                [0, 1]]

  V_T = [[0.8, -0.6]
            [0.6, 0.8]]

  original: http://www.machinelearning.ru/wiki/index.php?title=%D0%A1%D0%B8%D0%BD%D0%B3%D1%83%D0%BB%D1%8F%D1%80%D0%BD%D0%BE%D0%B5_%D1%80%D0%B0%D0%B7%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5
  '''
  A = np.array([[1, 2, 3],
                [5, 7, 8],
                [3, 6, 8]], dtype = float)
svd_test(A)

Origin matrix A: 
[[1. 2. 3.]
 [5. 7. 8.]
 [3. 6. 8.]] 
 
Матрица левых сингулярных векторов U: 
 [[-0.23   0.346 -0.909]
 [-0.727 -0.682 -0.075]
 [-0.646  0.644  0.409]] 
 
Матрица сингулярных чисел Sigma: 
 [[16.097  0.     0.   ]
 [ 0.     1.367  0.   ]
 [ 0.     0.     0.136]] 
 
Матрица правых сингулярных векторов V_T: 
 [[-0.361 -0.586 -0.726]
 [-0.827 -0.158  0.539]
 [ 0.43  -0.795  0.428]] 
 
Исходная матрица: 
 [[ 2.12300521 -1.20093008  5.38986232]
 [ 2.40055322 -3.18712345  8.54866003]
 [ 2.11838208 -4.5084873  10.59178926]] 
 


### Комментарии


#### Заира

Делаем так: нам нужно найти разложение X вида $U*Сигма*V_T$:
- находим собственные значения для матрицы A*A_T и собств вектора -> определим U и Сигму из этого

Cейчас (до вс) нужно научиться сортировать в сигме синг значения по убыванию и менять соответсвующие столбцы в U.
Что делать с матрицей V я подумаю и скажу в вс

#### Дима

__Сделать__

- nenene

#### Вадим

можете оставлять здесь комментарии, заметки и прикладывать картинки.

тыкни два раза по этому тексту чтобы редактировать его

#### Алена

можете оставлять здесь комментарии, заметки и прикладывать картинки.

тыкни два раза по этому тексту чтобы редактировать его

In [ ]:
МЯУ